import fs from 'node:fs';
import path from 'node:path';
import {isDeepStrictEqual} from 'node:util';
import {safeFile,sha} from '../management/files.mjs';
import {must,exact,plain} from '../pages/rules.mjs';
import {decode} from './decode.mjs';

export const contractPath='data/site-media-contract.json',statePath='data/site-media.json',stylePath='styles/site-media.generated.css';
export const capabilities=['media.library.v1','media.still-image.v1','media.usage.v1','media.shared-rebind.v1','snapshot.validation.v1'];
export const declaration={siteId:'krispykp',schemaVersion:1,protocolVersion:1,adapter:'still-image-usage-v1',requiredCapabilities:capabilities,stateFile:statePath,styleFile:stylePath,formats:['image/png','image/jpeg','image/webp'],maxBytes:8388608,minDimension:32,maxDimension:8192,maxPixels:16000000,maxImports:10,maxBatchBytes:33554432,maxAssets:100,maxManagedBytes:134217728,frames:['intrinsic','square','landscape','portrait'],fits:['contain','cover'],writable:['home.hero.image','managed-page-image-v2'],deletion:false};
export const empty=()=>({siteId:'krispykp',schemaVersion:1,assets:[],usages:[]});
export function canonicalAssetPath(root,file){let current=root;for(const segment of file.split('/')){if(fs.existsSync(current)){const aliases=fs.readdirSync(current).filter(name=>name.toLowerCase()===segment.toLowerCase());must(aliases.length===0||aliases.length===1&&aliases[0]===segment,'MEDIA_PATH','Case-aliased asset directories/files are refused.');}current=path.join(current,segment);}return safeFile(root,file,{existing:false});}
export function bytes(root,file,files=null){if(file.startsWith('assets/managed/images/'))canonicalAssetPath(root,file);return files?.get(file)??fs.readFileSync(safeFile(root,file));}
export function mediaReceipt(value){return Object.fromEntries(['mediaUsageImpact','mediaContractSha256','mediaStateSha256','usageInventorySha256','unusedImportsOmitted'].map(key=>[key,value[key]??(key.endsWith('Impact')||key==='unusedImportsOmitted'?[]:null)]));}
export function enabled(root){return fs.existsSync(safeFile(root,contractPath,{existing:false}));}
export function loadDeclaration(root,consumer){const data=bytes(root,contractPath);must(data.length<=16384,'MEDIA_MAPPING','Media declaration exceeds bounds.');let value;try{value=JSON.parse(data);}catch{must(false,'MEDIA_MAPPING','Malformed media declaration.');}must(isDeepStrictEqual(value,declaration),'ADMIN_UPDATE_REQUIRED','Unsupported media semantics.');if(consumer!==undefined)must(consumer?.protocolVersion===1&&Array.isArray(consumer.capabilities)&&capabilities.every(c=>consumer.capabilities.includes(c)),'ADMIN_UPDATE_REQUIRED','Media consumer capabilities require an update.');return {declaration:value,mediaContractSha256:sha(data)};}
export function assetRecord(proof){return {id:'asset.'+proof.sha256.toLowerCase(),path:'assets/managed/images/'+proof.sha256.toLowerCase()+'.'+proof.extension,sha256:proof.sha256,mime:proof.mime,width:proof.width,height:proof.height,bytes:proof.bytes};}
export function assetShape(asset){must(exact(asset,['id','path','sha256','mime','width','height','bytes'])&&/^[A-F0-9]{64}$/.test(asset.sha256)&&asset.id==='asset.'+asset.sha256.toLowerCase(),'MEDIA_ASSET','Invalid content asset identity.');const extension={'image/png':'png','image/jpeg':'jpg','image/webp':'webp'}[asset.mime];must(extension&&asset.path==='assets/managed/images/'+asset.sha256.toLowerCase()+'.'+extension&&Number.isInteger(asset.width)&&Number.isInteger(asset.height)&&asset.width>=32&&asset.height>=32&&asset.width<=8192&&asset.height<=8192&&asset.width*asset.height<=16000000&&Number.isInteger(asset.bytes)&&asset.bytes>0&&asset.bytes<=8388608,'MEDIA_ASSET','Invalid asset path/format/intrinsic bounds.');return asset;}
export function usageShape(value,asset,id){
  must(exact(value,['assetId','alt','frame','fit','position','crop'])&&value.assetId===asset.id,'MEDIA_USAGE','Usage requires exact supported fields and asset.');plain(value.alt,160);must(declaration.frames.includes(value.frame)&&declaration.fits.includes(value.fit),'MEDIA_USAGE','Unsupported frame/fit.');
  const p=value.position;must(exact(p,['mode','x','y'])&&['center','focal'].includes(p.mode)&&[p.x,p.y].every(n=>Number.isFinite(n)&&n>=0&&n<=1)&&(p.mode!=='center'||p.x===0.5&&p.y===0.5),'MEDIA_POSITION','Invalid normalized position/focal point.');
  if(value.crop!==null){const c=value.crop;must(exact(c,['x','y','width','height'])&&Object.values(c).every(Number.isFinite)&&c.x>=0&&c.y>=0&&c.width>0&&c.height>0&&c.x+c.width<=1&&c.y+c.height<=1&&c.width*asset.width>=32&&c.height*asset.height>=32,'MEDIA_CROP','Crop must stay within source and retain at least32 pixels per axis.');}
  if(value.frame==='intrinsic')must(value.fit==='contain'&&p.mode==='center'&&value.crop===null,'MEDIA_USAGE','Intrinsic usage has no crop/cover/focal override.');
  if(id==='home.hero.image')must(value.frame==='intrinsic'&&asset.width/asset.height>=0.25&&asset.width/asset.height<=4,'MEDIA_HOME','Home brand usage preserves intrinsic containment and approved aspect range.');
  return value;
}
export function loadState(root,files=null,{verify=true}={}){
  if(!enabled(root))return empty();loadDeclaration(root);const data=bytes(root,statePath,files);must(data.length<=1048576,'MEDIA_LIMIT','Media state exceeds bounds.');let value;try{value=JSON.parse(data);}catch{must(false,'MEDIA_MAPPING','Malformed media state.');}
  must(exact(value,['siteId','schemaVersion','assets','usages'])&&value.siteId==='krispykp'&&value.schemaVersion===1&&Array.isArray(value.assets)&&value.assets.length<=100&&Array.isArray(value.usages)&&value.usages.length<=1601,'MEDIA_MAPPING','Unsupported media state.');
  const assets=new Map();let total=0;for(const a of value.assets){assetShape(a);must(!assets.has(a.id),'MEDIA_ASSET','Duplicate asset.');assets.set(a.id,a);total+=a.bytes;if(verify){const raw=bytes(root,a.path,files);must(raw.length===a.bytes&&sha(raw)===a.sha256,'MEDIA_ASSET','Asset bytes differ from declared hash.');const proof=decode(raw,a.mime,'inspect');must(proof.clean&&proof.width===a.width&&proof.height===a.height,'MEDIA_ASSET','Asset fails decoded/metadata-free source proof.');}}
  must(total<=134217728,'MEDIA_LIMIT','Managed asset budget exceeded.');const seen=new Set();for(const row of value.usages){must(exact(row,['id','value'])&&typeof row.id==='string'&&(row.id==='home.hero.image'||/^page\.[a-z][a-z0-9-]*\.[a-z][a-z0-9-]*$/.test(row.id))&&!seen.has(row.id)&&assets.has(row.value?.assetId),'MEDIA_USAGE','Unknown/duplicate usage or asset.');seen.add(row.id);usageShape(row.value,assets.get(row.value.assetId),row.id);}return value;
}
export function targetIds(registry){const targets=new Map([['home.hero.image',{id:'home.hero.image',file:'index.html',route:'/',tag:'img',parent:null}]]);function visit(node,page,parent){const id=page.id+'.'+node.id;if(node.kind==='image'&&node.media===true)targets.set(id,{id,file:page.slug+'/index.html',route:'/'+page.slug+'/',tag:'img',parent});for(const child of node.children||[])visit(child,page,id);}for(const page of registry.pages)for(const node of page.components)visit(node,page,page.id);return targets;}
export function lookup(state,id){const row=state.usages.find(u=>u.id===id);must(row,'MEDIA_USAGE','Declared media image has no usage value.');const asset=state.assets.find(a=>a.id===row.value.assetId);must(asset,'MEDIA_ASSET','Usage asset is missing.');return {value:row.value,asset};}
export function consumerCheck(value){must(value?.protocolVersion===1&&Array.isArray(value.capabilities)&&capabilities.every(c=>value.capabilities.includes(c)),'ADMIN_UPDATE_REQUIRED','Explicit current media consumer handshake required.');}
