import fs from 'node:fs';
import {isDeepStrictEqual} from 'node:util';
import {must,exact,loadRegistry} from '../pages/rules.mjs';
import {safeFile,sha} from '../management/files.mjs';
import {pageProposal} from '../pages/project.mjs';
import {pageDocument,partials,generatedStyle} from '../pages/shell.mjs';
import {admission} from './decode.mjs';
import {loadMedia} from './contract.mjs';
import {enabled,loadState,assetRecord,canonicalAssetPath,usageShape,targetIds,consumerCheck,statePath,stylePath,contractPath} from './model.mjs';
import {sharedScope} from './refs.mjs';
import {imageMarkup,stylesheet,styleLink} from './render.mjs';

function set(root,files,file,text){const target=safeFile(root,file,{existing:false}),old=fs.existsSync(target)?fs.readFileSync(target):null,eol=old?.toString().includes('\r\n')?'\r\n':'\n',data=Buffer.from(text.replaceAll('\r\n','\n').replaceAll('\n',eol));if(!old||!data.equals(old))files.set(file,data);else files.delete(file);}
export function projectMedia(root,files,request,consumer){
  if(!enabled(root)){must(!request.mediaOperations?.length,'ADMIN_UPDATE_REQUIRED','Source has no media contract.');return {expectedSources:[],mediaUsageImpact:[]};}
  const operations=request.mediaOperations??[];must(Array.isArray(operations)&&operations.length<=100,'MEDIA_REQUEST','Media operation batch exceeds bounds.');
  const original=loadState(root),registry=request.pageOperations?.length?pageProposal(root,request,consumer).registry:loadRegistry(root),targets=targetIds(registry),pruned=original.usages.filter(u=>!targets.has(u.id));
  if(!operations.length&&!pruned.length)return {expectedSources:[],mediaUsageImpact:[]};
  consumerCheck(consumer.media);const loaded=loadMedia(root,consumer.media);must(request.mediaContractSha256===loaded.mediaContractSha256&&request.mediaStateSha256===loaded.mediaStateSha256&&request.usageInventorySha256===loaded.usageInventorySha256,'STALE_MEDIA','Pinned media declaration/state/usage inventory changed.');
  const state=structuredClone(original);state.usages=state.usages.filter(u=>targets.has(u.id));const imports=new Map(),seen=new Set(),touched=new Set(),impact=[];let total=0;
  for(const op of operations){must(exact(op,['id','kind','expectedOld','value'])&&typeof op.id==='string'&&!seen.has(op.kind+':'+op.id),'MEDIA_REQUEST','Malformed/duplicate media operation.');seen.add(op.kind+':'+op.id);must(['importAsset','setUsage','rebindShared'].includes(op.kind),'MEDIA_REQUEST','Unsupported media/deletion operation.');if(op.kind!=='importAsset')continue;must(op.expectedOld===null&&imports.size<10,'MEDIA_UPLOAD','Import requires absence proof and bounded import count.');const proof=admission(op.value),asset=assetRecord(proof);must(op.id===asset.id&&!state.assets.some(a=>a.id===op.id)&&!imports.has(op.id),'MEDIA_ASSET','Imported sanitized identity disagrees or already exists; reuse the declared asset.');total+=Buffer.byteLength(op.value.base64,'base64');must(total<=33554432,'MEDIA_LIMIT','Import batch exceeds encoded byte budget.');imports.set(op.id,{asset,data:proof.data});}
  const assetFor=id=>state.assets.find(a=>a.id===id)||imports.get(id)?.asset;
  for(const op of operations.filter(o=>o.kind==='setUsage')){must(targets.has(op.id)&&!touched.has(op.id),'MEDIA_TARGET','Undeclared/duplicate media target.');const before=original.usages.find(u=>u.id===op.id)?.value??null;must(isDeepStrictEqual(op.expectedOld,before),'STALE_VALUE','Media usage expected-old differs from immutable baseline.');must(!request.operations?.some(o=>o.id===op.id&&o.kind==='replaceImage'),'MEDIA_CONFLICT','Legacy image and media usage cannot edit the same target in one batch.');const asset=assetFor(op.value?.assetId);must(asset,'MEDIA_ASSET','Usage names no imported/existing asset.');usageShape(op.value,asset,op.id);touched.add(op.id);const row={id:op.id,value:op.value},index=state.usages.findIndex(u=>u.id===op.id);if(index<0)state.usages.push(row);else state.usages[index]=row;impact.push({id:op.id,kind:'setUsage',before,after:op.value,selectedUsageOnly:true,originalAssetUnchanged:true});}
  for(const op of operations.filter(o=>o.kind==='rebindShared')){const scope=sharedScope(original,loaded,op.id);must(scope.complete&&exact(op.expectedOld,['assetSha256','usageInventorySha256','usages'])&&isDeepStrictEqual(op.expectedOld,{assetSha256:scope.assetSha256,usageInventorySha256:scope.usageInventorySha256,usages:scope.usages}),'MEDIA_SHARED_SCOPE','Shared rebinding requires exact complete editable usage proof.');must(exact(op.value,['assetId'])&&assetFor(op.value.assetId),'MEDIA_ASSET','Shared value requires one known replacement asset.');must(!state.usages.some(r=>r.value.assetId===op.id&&!scope.usages.some(s=>s.id===r.id)),'MEDIA_CONFLICT','New usage changes invalidate baseline shared scope.');for(const before of scope.usages){must(targets.has(before.id)&&!touched.has(before.id)&&!request.operations?.some(o=>o.id===before.id&&o.kind==='replaceImage'),'MEDIA_CONFLICT','Shared and selected/legacy operations conflict.');touched.add(before.id);const value={...before.value,assetId:op.value.assetId};usageShape(value,assetFor(value.assetId),before.id);state.usages[state.usages.findIndex(r=>r.id===before.id)]={id:before.id,value};impact.push({id:before.id,kind:'rebindShared',before:before.value,after:value,sharedAssetId:op.id,completeUsageReview:true,originalAssetUnchanged:true});}}
  const referenced=new Set(state.usages.map(r=>r.value.assetId));for(const [id,imported] of imports)if(referenced.has(id)){const target=canonicalAssetPath(root,imported.asset.path);if(fs.existsSync(target))must(sha(fs.readFileSync(target))===imported.asset.sha256,'MEDIA_COLLISION','Derived asset path contains different bytes.');else files.set(imported.asset.path,imported.data);state.assets.push(imported.asset);}
  state.assets.sort((a,b)=>a.id.localeCompare(b.id));state.usages.sort((a,b)=>a.id.localeCompare(b.id));must(state.assets.length<=100&&state.assets.reduce((n,a)=>n+a.bytes,0)<=134217728,'MEDIA_LIMIT','Managed catalog budget exceeded.');for(const row of state.usages){must(targets.has(row.id),'MEDIA_TARGET','Orphan usage is not writable.');usageShape(row.value,assetFor(row.value.assetId),row.id);}for(const target of targets.values())if(target.id!=='home.hero.image')must(state.usages.some(u=>u.id===target.id),'MEDIA_USAGE','New media component needs a typed usage in the same batch.');
  const expectedSources=[contractPath,statePath,stylePath,'data/site-pages.json','data/site-pages-contract.json','styles/site-pages.generated.css','index.html',...loadRegistry(root).pages.map(p=>p.slug+'/index.html'),...original.assets.map(a=>a.path)];
  if(!isDeepStrictEqual(state,original))set(root,files,statePath,JSON.stringify(state,null,2)+'\n');set(root,files,stylePath,stylesheet(state));
  const beforeHome=original.usages.find(u=>u.id==='home.hero.image'),home=state.usages.find(u=>u.id==='home.hero.image');if(home){let source=files.get('index.html')?.toString('utf8')??fs.readFileSync(safeFile(root,'index.html'),'utf8');const after=imageMarkup(root,home.id,'class="hero-logo" data-kkp-manage-id="home.hero.image"',files),before=beforeHome?imageMarkup(root,beforeHome.id,'class="hero-logo" data-kkp-manage-id="home.hero.image"'):[...source.matchAll(/<img\b[^>]*data-kkp-manage-id="home\.hero\.image"[^>]*>/g)].map(m=>m[0]);must(beforeHome?source.includes(before):before.length===1,'MEDIA_RENDER','Home adapter source is ambiguous.');source=source.replace(beforeHome?before:before[0],after);set(root,files,'index.html',styleLink(source,true));}
  return {expectedSources:[...new Set(expectedSources)],mediaUsageImpact:impact,mediaContractSha256:loaded.mediaContractSha256,mediaStateSha256:loaded.mediaStateSha256,usageInventorySha256:loaded.usageInventorySha256,registry,state,unusedImportsOmitted:[...imports.keys()].filter(id=>!referenced.has(id))};
}
export function finishMedia(root,files,media){if(!media.registry)return;const templates=partials(root);for(const page of media.registry.pages)set(root,files,page.slug+'/index.html',pageDocument(page,media.registry,root,templates,files));set(root,files,'styles/site-pages.generated.css',generatedStyle(media.registry,root,files));}
