import {must,escape} from '../pages/rules.mjs';
import {loadState,lookup,usageShape} from './model.mjs';
export function imageMarkup(root,id,attributes,files=null){const {value,asset}=lookup(loadState(root,files),id);usageShape(value,asset,id);const image=`<img ${attributes} data-kkp-media-id="${id}" src="/${asset.path}" alt="${escape(value.alt)}" width="${asset.width}" height="${asset.height}" loading="lazy" decoding="async">`;return `<span class="managed-media-frame" data-kkp-media-frame="${id}"><span class="managed-media-crop">${image}</span></span>`;}
export function usageCss(id,value,asset){
  usageShape(value,asset,id);const q=`[data-kkp-media-frame="${id}"]`,crop=value.crop||{x:0,y:0,width:1,height:1},ratio=asset.width*crop.width/(asset.height*crop.height),frame={square:1,landscape:16/9,portrait:3/4}[value.frame],n=v=>Number(v.toFixed(8));
  if(!frame)return `${q} { display:block; max-width:100%; } ${q} > .managed-media-crop { display:block; } ${q} > .managed-media-crop > img { display:block; width:100%; height:auto; max-width:none; }\n`+(id==='home.hero.image'?`${q} { width:150px; } @media (max-width:700px) { ${q} { width:88px; } } @media (max-width:420px) { ${q} { width:104px; } }\n`:'');
  let width=100,height=100;if((value.fit==='cover'&&ratio>frame)||(value.fit==='contain'&&ratio<frame))width=100*ratio/frame;else height=100*frame/ratio;
  return `${q} { display:block; position:relative; overflow:hidden; width:100%; max-width:100%; aspect-ratio:${n(frame)}; } ${q} > .managed-media-crop { display:block; position:absolute; overflow:hidden; width:${n(width)}%; height:${n(height)}%; left:${n((100-width)*value.position.x)}%; top:${n((100-height)*value.position.y)}%; } ${q} img { display:block; position:absolute; max-width:none; width:${n(100/crop.width)}%; height:${n(100/crop.height)}%; left:${n(-100*crop.x/crop.width)}%; top:${n(-100*crop.y/crop.height)}%; }\n`;
}
export function stylesheet(state){return '/* Website-owned bounded media usage projection. */\n'+state.usages.map(row=>usageCss(row.id,row.value,state.assets.find(a=>a.id===row.value.assetId))).join('');}
export function styleLink(source,used){const line='<link rel="stylesheet" href="/styles/site-media.generated.css">';if(used&&!source.includes(line)){const anchor='<link rel="stylesheet" href="/styles/command-deck.css">';must(source.includes(anchor),'MEDIA_RENDER','Missing trusted stylesheet anchor.');return source.replace(anchor,anchor+(source.includes('\r\n')?'\r\n':'\n')+line);}if(!used)return source.replace(/\r?\n<link rel="stylesheet" href="\/styles\/site-media.generated.css">/,'');return source;}
