import fs from 'node:fs';
import {isDeepStrictEqual} from 'node:util';
import {safeFile,sha,requireThat as must} from '../management/files.mjs';
import {literals} from './literal.mjs';
import {musicProjection,videoProjection} from './runtime.mjs';

export const contractPath='data/site-structured-contract.json',statePath='data/site-structured-content.json',outputPath='data/site-structured.generated.js';
export const capabilities=['structured.music.v1','structured.lyrics.v1','structured.video.v1','structured.artwork.v1','structured.selection.v1','structured.public-filter.v1','snapshot.validation.v1'];
export const declaration={siteId:'krispykp',schemaVersion:1,protocolVersion:1,adapter:'literal-overlay-v1',requiredCapabilities:capabilities,stateFile:statePath,outputFile:outputPath,sourceFiles:['data/tracks.js','data/lyrics.js','data/video-playlists.config.mjs','data/videos.generated.js'],routes:['/','/music/','/videos/'],maxOperations:500,maxTracks:500,maxPlaylists:100,maxCategories:100,maxTabs:200,maxVideos:5000,maxLabel:200,maxLyrics:32000,maxStateBytes:4194304,maxSourceBytes:8388608,maxImportedOccurrences:20000,maxLiteralNodes:500000,maxLiteralDepth:32,maxFeatureOnlyVideos:1,projectionVersion:1,maxLatestPerCategory:16,maxOccurrences:22000,externalRefresh:false,deletion:false,audioImport:false};
export const empty=()=>({siteId:'krispykp',schemaVersion:1,music:{tracks:[],playlists:[],lyrics:[],order:[]},videos:{videos:[],categories:[],tabs:[],tabOrders:[],order:[],featured:null}});
export const exact=(v,keys)=>v&&typeof v==='object'&&!Array.isArray(v)&&isDeepStrictEqual(Object.keys(v).sort(),[...keys].sort());
export const text=(v,max=200,allowEmpty=false,multiline=false)=>must(typeof v==='string'&&(allowEmpty||v.trim().length>0)&&v.length<=max&&Buffer.byteLength(v)<=max*4&&!(multiline?/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/:/[\x00-\x1f\x7f]/).test(v),'STRUCTURED_VALUE','Expected bounded plain text.');
const data=(root,p,mode='script',files=null)=>literals((files?.get(p)??fs.readFileSync(safeFile(root,p))).toString('utf8'),mode);
export function consumerCheck(value){must(value?.protocolVersion===1&&Array.isArray(value.capabilities)&&capabilities.every(c=>value.capabilities.includes(c)),'ADMIN_UPDATE_REQUIRED','Structured content requires the declared current consumer capabilities.');}
export function enabled(root){return fs.existsSync(safeFile(root,contractPath,{existing:false}));}
export function artworkTargets(root){return enabled(root)?sources(root).tracks.map(t=>({id:'track.'+t.id,file:outputPath,route:'/music/',routes:['/','/music/'],tag:'img',parent:null})):[];}
const unique=(rows,label)=>{must(Array.isArray(rows),'STRUCTURED_MAPPING','Missing '+label+'.');const ids=rows.map(r=>r.id);must(ids.every(id=>typeof id==='string'&&/^[a-z0-9][a-z0-9-]{0,99}$/.test(id))&&new Set(ids).size===ids.length,'STRUCTURED_MAPPING','Duplicate/invalid '+label+' identity.');};
export function sources(root,files=null){
  const trackSource=data(root,'data/tracks.js','script',files).values,lyricSource=data(root,'data/lyrics.js','script',files).values,videoSource=data(root,'data/videos.generated.js','script',files).values,config=data(root,'data/video-playlists.config.mjs','export',files).values;
  must(exact(trackSource,['KRISPY_TRACKS','KRISPY_PLAYLISTS'])&&exact(lyricSource,['KRISPY_LYRICS'])&&exact(videoSource,['KRISPY_VIDEO_DATA'])&&exact(config,['VIDEO_PLAYLISTS']),'STRUCTURED_LITERAL','Source assignments differ from declared grammar.');
  const tracks=trackSource.KRISPY_TRACKS,playlists=trackSource.KRISPY_PLAYLISTS,lyrics=lyricSource.KRISPY_LYRICS,categories=config.VIDEO_PLAYLISTS,video=videoSource.KRISPY_VIDEO_DATA;
  unique(tracks,'tracks');unique(playlists,'playlists');unique(categories,'categories');const tabs=categories.flatMap(c=>c.subTabs||[]);unique(tabs,'tabs');
  must(tracks.length<=500&&playlists.length<=100&&categories.length<=100&&tabs.length<=200&&lyrics&&typeof lyrics==='object'&&!Array.isArray(lyrics)&&video&&Array.isArray(video.categories),'STRUCTURED_LIMIT','Source structure/count exceeds contract.');
  for(const t of tracks){text(t.name);text(t.artist);text(t.album,200,true);must(typeof t.available==='boolean'&&typeof t.file==='string'&&t.file.startsWith('/media/music/')&&t.file.endsWith('.mp3')&&typeof t.art==='string'&&t.art.startsWith('/'),'STRUCTURED_MAPPING','Unsupported legacy track fields.');safeFile(root,t.file.slice(1));safeFile(root,t.art.slice(1));}
  const trackIds=new Set(tracks.map(t=>t.id));for(const p of playlists){text(p.name);must(['ALL','CUSTOM'].includes(p.tracks)||Array.isArray(p.tracks)&&p.tracks.length<=500&&new Set(p.tracks).size===p.tracks.length&&p.tracks.every(id=>trackIds.has(id)),'STRUCTURED_MAPPING','Invalid authored playlist references.');}
  for(const v of Object.values(lyrics)){must(v&&typeof v==='object','STRUCTURED_MAPPING','Invalid lyric record.');text(v.title);text(v.lyrics,32000,true,true);}
  must(video.categories.length===categories.length&&categories.every(c=>video.categories.some(v=>v.id===c.id)),'STRUCTURED_MAPPING','Authored/generated category IDs differ; import remains read-only until reconciled.');
  const videos=new Map();let tabOccurrences=0;for(const c of video.categories){must(Array.isArray(c.latest)&&c.latest.length<=16,'STRUCTURED_LIMIT','Generated latest list exceeds16/category.');for(const tab of c.subTabs||[]){must(tabs.some(t=>t.id===tab.id&&t.playlistId===tab.playlistId),'STRUCTURED_MAPPING','Generated tab differs from declared playlist source.');must(Array.isArray(tab.items),'STRUCTURED_MAPPING','Missing generated tab items.');for(const item of tab.items){must(++tabOccurrences<=20000&&/^[A-Za-z0-9_-]{11}$/.test(item.videoId),'STRUCTURED_MAPPING','Invalid/derived imported video source.');if(video._kkpStructuredProjection===1&&item._kkpDerived===1)must(item._kkpOriginal?.videoId===item.videoId,'STRUCTURED_MAPPING','Generated provenance must retain its exact original identity.');if(!videos.has(item.videoId))videos.set(item.videoId,video._kkpStructuredProjection===1&&item._kkpDerived===1&&item._kkpOriginal||item);}}}
  must(videos.size<=5000,'STRUCTURED_LIMIT','Imported video limit exceeded.');
  must(video._kkpStructuredProjection===undefined||video._kkpStructuredProjection===1,'ADMIN_UPDATE_REQUIRED','Unknown generated structured projection version.');const global=video._kkpStructuredProjection===1?(video._kkpOriginalFeatured||video.featured):video.featured;if(global?.videoId&&!videos.has(global.videoId)){must(/^[A-Za-z0-9_-]{11}$/.test(global.videoId),'STRUCTURED_MAPPING','Invalid legacy global feature.');videos.set(global.videoId,global);}
  must(videos.size<=5001,'STRUCTURED_LIMIT','Imported video limit exceeded.');
  const occurrences=[];for(const c of video.categories){for(const [index,item] of (c.latest||[]).entries())occurrences.push({id:item.videoId,kind:'latest',categoryId:c.id,tabId:null,index,title:(video._kkpStructuredProjection===1&&item._kkpDerived===1&&item._kkpOriginal||item).title??null});for(const t of c.subTabs||[])for(const [index,item] of (t.items||[]).entries())occurrences.push({id:item.videoId,kind:'tab',categoryId:c.id,tabId:t.id,index,title:(video._kkpStructuredProjection===1&&item._kkpDerived===1&&item._kkpOriginal||item).title??null});}if(global?.videoId)occurrences.push({id:global.videoId,kind:'global-feature',categoryId:null,tabId:null,index:0,title:global.title??null});
  must(occurrences.length<=22000,'STRUCTURED_LIMIT','Imported occurrence inventory exceeds bounds.');const conflicts=[...videos.keys()].map(id=>({id,field:'title',values:[...new Set(occurrences.filter(o=>o.id===id).map(o=>o.title))]})).filter(c=>c.values.length>1);const featureOnly=[...videos.keys()].filter(id=>!occurrences.some(o=>o.id===id&&o.kind==='tab'));const unresolvedFeatures=categories.filter(c=>c.featuredVideoId&&!videos.has(c.featuredVideoId)).map(c=>({categoryId:c.id,videoId:c.featuredVideoId,editable:false,reason:'Existing feature reference has no imported metadata; preserve or explicitly choose a known record.'}));
  return {tracks,playlists,lyrics,categories,tabs,video,videos,occurrences,conflicts,featureOnly,unresolvedFeatures,orphans:Object.keys(lyrics).filter(id=>!trackIds.has(id))};
}
export function validateState(state,source){
  must(exact(state,['siteId','schemaVersion','music','videos'])&&state.siteId==='krispykp'&&state.schemaVersion===1&&exact(state.music,['tracks','playlists','lyrics','order'])&&exact(state.videos,['videos','categories','tabs','tabOrders','order','featured']),'ADMIN_UPDATE_REQUIRED','Unsupported authored structured state.');
  const seen=(rows,max)=>{must(Array.isArray(rows)&&rows.length<=max&&new Set(rows.map(r=>r?.id)).size===rows.length,'STRUCTURED_LIMIT','Duplicate/unbounded authored rows.');};
  const order=(ids,known,optional=true)=>{must(Array.isArray(ids)&&(optional&&!ids.length||ids.length===known.length&&new Set(ids).size===ids.length&&ids.every(id=>known.includes(id))),'STRUCTURED_ORDER','Order must be an exact known-ID permutation.');};
  seen(state.music.tracks,500);for(const row of state.music.tracks){must(exact(row,['id','name','artist','album','available','visible'])&&source.tracks.some(t=>t.id===row.id)&&typeof row.available==='boolean'&&typeof row.visible==='boolean','STRUCTURED_VALUE','Unknown track or unsupported track fields.');text(row.name);text(row.artist);text(row.album,200,true);}
  seen(state.music.playlists,100);for(const row of state.music.playlists){const old=source.playlists.find(p=>p.id===row.id);must(exact(row,['id','name','tracks'])&&old,'STRUCTURED_VALUE','Unknown playlist.');text(row.name);must(typeof old.tracks==='string'?row.tracks===old.tracks:Array.isArray(row.tracks)&&row.tracks.length<=500&&new Set(row.tracks).size===row.tracks.length&&row.tracks.every(id=>source.tracks.some(t=>t.id===id)),'STRUCTURED_REFERENCE','Playlist mode/references invalid.');}
  seen(state.music.lyrics,500);for(const row of state.music.lyrics){must(exact(row,['id','title','lyrics'])&&source.tracks.some(t=>t.id===row.id),'STRUCTURED_REFERENCE','New lyric association must name a known track; legacy orphan remains locked.');text(row.title);text(row.lyrics,32000,true,true);}
  order(state.music.order,source.tracks.map(t=>t.id));
  seen(state.videos.videos,5001);for(const row of state.videos.videos){must(exact(row,['id','title','note','visible'])&&source.videos.has(row.id)&&typeof row.visible==='boolean','STRUCTURED_REFERENCE','Unknown imported video or invalid visibility.');if(row.title!==null)text(row.title);if(row.note!==null)text(row.note,32000,true,true);}
  const eligible=id=>id===''||source.videos.has(id)&&state.videos.videos.find(v=>v.id===id)?.visible!==false;
  seen(state.videos.categories,100);for(const r of state.videos.categories){must(exact(r,['id','title','featuredVideoId'])&&source.categories.some(c=>c.id===r.id)&&(eligible(r.featuredVideoId)||source.categories.some(c=>c.id===r.id&&c.featuredVideoId===r.featuredVideoId&&!source.videos.has(r.featuredVideoId))),'STRUCTURED_REFERENCE','Category identity/feature must be known and visible.');text(r.title);}
  seen(state.videos.tabs,200);for(const r of state.videos.tabs){must(exact(r,['id','title','videoIds'])&&source.tabs.some(t=>t.id===r.id)&&Array.isArray(r.videoIds)&&r.videoIds.length<=5000&&new Set(r.videoIds).size===r.videoIds.length&&r.videoIds.every(id=>source.videos.has(id)&&!(source.featureOnly||[]).includes(id)),'STRUCTURED_REFERENCE','Unknown tab/imported membership.');text(r.title);}
  seen(state.videos.tabOrders,100);for(const r of state.videos.tabOrders){const c=source.categories.find(c=>c.id===r.id);must(exact(r,['id','ids'])&&c&&c.id!=='latest','STRUCTURED_ORDER','Unknown ordinary category order.');order(r.ids,(c.subTabs||[]).map(t=>t.id),false);}
  order(state.videos.order,source.categories.map(c=>c.id));must(state.videos.featured===null||eligible(state.videos.featured),'STRUCTURED_REFERENCE','Global feature must be known and visible.');return state;
}
export function load(root,consumer,files=null){
  const bytes=fs.readFileSync(safeFile(root,contractPath));must(bytes.length<=16384&&isDeepStrictEqual(literals(bytes.toString(),'json').data,declaration),'ADMIN_UPDATE_REQUIRED','Unsupported structured declaration.');if(consumer!==undefined)consumerCheck(consumer);
  const source=sources(root,files),raw=files?.get(statePath)??fs.readFileSync(safeFile(root,statePath));must(raw.length<=4194304,'STRUCTURED_LIMIT','Authored state exceeds4MiB.');const state=validateState(literals(raw.toString(),'json').data,source);
  return {source,state,structuredContractSha256:sha(bytes),structuredStateSha256:sha(raw),sourceHashes:Object.fromEntries(declaration.sourceFiles.map(p=>[p,sha(fs.readFileSync(safeFile(root,p)))]))};
}
export function view(loaded){const {state:s,source:b}=loaded;return {tracks:b.tracks.map(t=>s.music.tracks.find(r=>r.id===t.id)||{id:t.id,name:t.name,artist:t.artist,album:t.album,available:t.available,visible:true}),playlists:b.playlists.map(p=>s.music.playlists.find(r=>r.id===p.id)||{id:p.id,name:p.name,tracks:p.tracks}),lyrics:b.tracks.map(t=>s.music.lyrics.find(r=>r.id===t.id)|| (b.lyrics[t.id]?{id:t.id,title:b.lyrics[t.id].title,lyrics:b.lyrics[t.id].lyrics}:{id:t.id,title:t.name,lyrics:null})),catalogueOrder:s.music.order.length?s.music.order:b.tracks.map(t=>t.id),videos:[...b.videos].map(([id])=>s.videos.videos.find(r=>r.id===id)||{id,title:null,note:null,visible:true}),categories:b.categories.map(c=>s.videos.categories.find(r=>r.id===c.id)||{id:c.id,title:c.title,featuredVideoId:c.featuredVideoId||''}),tabs:b.video.categories.flatMap(c=>(c.subTabs||[]).map(t=>s.videos.tabs.find(r=>r.id===t.id)||{id:t.id,title:t.title,videoIds:t.items.map(v=>v.videoId)})),categoryOrder:s.videos.order.length?s.videos.order:b.categories.map(c=>c.id),tabOrders:b.categories.filter(c=>c.id!=='latest').map(c=>s.videos.tabOrders.find(r=>r.id===c.id)||{id:c.id,ids:c.subTabs.map(t=>t.id)}),featured:s.videos.featured===null?b.video.featured?.videoId||'':s.videos.featured};}
export function generated(state,artwork={}){const encode=v=>JSON.stringify(v).replaceAll('<','\\u003c').replaceAll('\u2028','\\u2028').replaceAll('\u2029','\\u2029');return '/* Website-owned structured overlay; generated, read-only. */\n(function(){\nconst state='+encode(state)+';\nconst artwork='+encode(artwork)+';\nwindow.KRISPY_STRUCTURED_ARTWORK=artwork;\nconst music='+musicProjection.toString().replaceAll('\r\n','\n')+';\nconst video='+videoProjection.toString().replaceAll('\r\n','\n')+';\nif(window.KRISPY_TRACKS){const projected=music(window.KRISPY_TRACKS,window.KRISPY_PLAYLISTS||[],window.KRISPY_LYRICS||{},state.music,artwork);window.KRISPY_TRACKS=projected.tracks;window.KRISPY_PLAYLISTS=projected.playlists;if(window.KRISPY_LYRICS)window.KRISPY_LYRICS=projected.lyrics;}\nif(window.KRISPY_VIDEO_DATA)window.KRISPY_VIDEO_DATA=video(window.KRISPY_VIDEO_DATA,state.videos);\n})();\n';}
