import fs from 'node:fs';
import {isDeepStrictEqual} from 'node:util';
import {safeFile,sha,requireThat as must} from '../management/files.mjs';
import {loadState} from '../media/model.mjs';
import {load,view,validateState,exact,enabled,contractPath,statePath,outputPath,generated,consumerCheck} from './model.mjs';

export function artwork(root,files=null){const state=loadState(root,files),out={};for(const row of state.usages.filter(r=>r.id.startsWith('track.'))){const asset=state.assets.find(a=>a.id===row.value.assetId);out[row.id.slice(6)]={src:'/'+asset.path,alt:row.value.alt,width:asset.width,height:asset.height,usageId:row.id};}return out;}
export function loadStructured(root,consumer){const value=load(root,consumer);const raw=fs.readFileSync(safeFile(root,outputPath),'utf8');must(raw.replaceAll('\r\n','\n')===generated(value.state,artwork(root)),'STRUCTURED_PARITY','Generated structured runtime disagrees with authored state/media.');return {...value,state:'COMPATIBLE',authoredState:value.state,readOnly:false,values:view(value),orphans:value.source.orphans,subTabIdentity:'global',occurrences:value.source.occurrences,importedTitleConflicts:value.source.conflicts,featureOnly:value.source.featureOnly,unresolvedFeatures:value.source.unresolvedFeatures,importedMetadata:[...value.source.videos].map(([id,v])=>({id,title:v.title??null,duration:v.duration??null,publishedAt:v.publishedAt??null,videoPublishedAt:v.videoPublishedAt??null,playlistAddedAt:v.playlistAddedAt??null,position:v.position??null,thumbnail:v.thumbnail??null,descriptionSha256:typeof v.description==='string'?sha(v.description):null})),externalRefresh:{supported:false,reason:'Offline projection only; current external generator requires credentials.'}};}
export function readStructured(root,consumer){try{consumerCheck(consumer);const loaded=loadStructured(root,consumer);return {...loaded,source:undefined,expectedFiles:expectedFiles(root)};}catch(error){return {state:error.code==='ADMIN_UPDATE_REQUIRED'?'ADMIN_UPDATE_REQUIRED':'UNVERIFIED',readOnly:true,diagnostics:[{severity:'blocking',code:error.code||'STRUCTURED_MAPPING',message:error.message}]};}}
export function expectedFiles(root){const loaded=load(root);return Object.fromEntries([contractPath,statePath,outputPath,...Object.keys(loaded.sourceHashes),'data/site-media.json'].map(p=>[p,sha(fs.readFileSync(safeFile(root,p)))]));}
function write(root,files,p,value){const raw=fs.readFileSync(safeFile(root,p)),eol=raw.toString().includes('\r\n')?'\r\n':'\n',bytes=Buffer.from(value.replaceAll('\r\n','\n').replaceAll('\n',eol));if(!bytes.equals(raw))files.set(p,bytes);else files.delete(p);}
export function projectStructured(root,files,request,consumer){
  const operations=request.structuredOperations??[];must(Array.isArray(operations)&&operations.length<=500,'STRUCTURED_REQUEST','Structured operation batch exceeds500.');
  const mediaChanged=(request.mediaOperations||[]).some(o=>o.id?.startsWith('track.')||o.kind==='rebindShared'&&loadState(root).usages.some(u=>u.id.startsWith('track.')&&u.value.assetId===o.id));
  if(!operations.length&&!mediaChanged)return {expectedSources:[],structuredImpact:[]};
  must(enabled(root),'ADMIN_UPDATE_REQUIRED','Source does not declare structured editing.');const loaded=loadStructured(root,consumer.structured);consumerCheck(consumer.structured);
  must(request.structuredContractSha256===loaded.structuredContractSha256&&request.structuredStateSha256===loaded.structuredStateSha256,'STALE_STRUCTURED','Structured declaration/state pin changed.');
  const state=structuredClone(loaded.authoredState),values=loaded.values,seen=new Set(),impact=[];
  const rows={setTrack:['music','tracks','tracks'],setPlaylist:['music','playlists','playlists'],setLyrics:['music','lyrics','lyrics'],setVideo:['videos','videos','videos'],setCategory:['videos','categories','categories'],setTab:['videos','tabs','tabs'],setTabOrder:['videos','tabOrders','tabOrders']};
  for(const op of operations){must(exact(op,['id','kind','expectedOld','value'])&&typeof op.id==='string'&&!seen.has(op.kind+':'+op.id),'STRUCTURED_REQUEST','Malformed/duplicate structured operation.');seen.add(op.kind+':'+op.id);let before;const prior=structuredClone(state);
    if(Object.hasOwn(rows,op.kind)){const [group,key,viewKey]=rows[op.kind];before=values[viewKey].find(r=>r.id===op.id);must(before&&op.value?.id===op.id,'STRUCTURED_REFERENCE','Unknown/renamed structured identity.');const index=state[group][key].findIndex(r=>r.id===op.id);if(index<0)state[group][key].push(op.value);else state[group][key][index]=op.value;}
    else if(op.kind==='setCatalogueOrder'||op.kind==='setCategoryOrder'){const music=op.kind==='setCatalogueOrder';must(op.id===(music?'music.catalogue':'videos.categories'),'STRUCTURED_REFERENCE','Order target differs from declared identity.');before=music?values.catalogueOrder:values.categoryOrder;state[music?'music':'videos'].order=op.value;}
    else if(op.kind==='setFeaturedVideo'){must(op.id==='videos.featured','STRUCTURED_REFERENCE','Unknown global feature target.');before=values.featured;state.videos.featured=op.value;}
    else must(false,'STRUCTURED_REQUEST','Unsupported structured operation; source creation/deletion/refresh are not declared.');
    must(isDeepStrictEqual(before,op.expectedOld),'STALE_VALUE','Structured expected-old differs from baseline.',op.id);if(isDeepStrictEqual(before,op.value)){Object.assign(state,prior);impact.push({id:op.id,kind:op.kind,noOp:true});continue;}impact.push({id:op.id,kind:op.kind,before,after:op.value,routes:op.kind.includes('Video')||op.kind.includes('Category')||op.kind.includes('Tab')?['/','/videos/']:['/','/music/'],sourcePreserved:true,affectedOccurrences:op.kind==='setVideo'?loaded.source.occurrences.filter(o=>o.id===op.id):[]});
  }
  validateState(state,loaded.source);for(const group of ['music','videos'])for(const key of Object.keys(state[group]))if(Array.isArray(state[group][key])&&key!=='order')state[group][key].sort((a,b)=>a.id.localeCompare(b.id,'en'));
  const serialized=JSON.stringify(state,null,2)+'\n',runtime=generated(state,artwork(root,files));must(Buffer.byteLength(serialized)<=4194304&&Buffer.byteLength(runtime)<=8388608,'STRUCTURED_LIMIT','Authored/generated structured output exceeds4/8MiB.');
  if(!isDeepStrictEqual(state,loaded.authoredState))write(root,files,statePath,serialized);write(root,files,outputPath,runtime);
  return {expectedSources:Object.keys(expectedFiles(root)),structuredImpact:impact,structuredContractSha256:loaded.structuredContractSha256,structuredStateSha256:loaded.structuredStateSha256,structuredSourceHashes:loaded.sourceHashes};
}
