import fs from 'node:fs';
import {must,escape,origin} from './rules.mjs';
import {safeFile,sha} from '../management/files.mjs';
import {composition} from './components.mjs';

export const partialNames=['header','footer','footer-privacy','background','background-tournaments'];
export function partials(root){return Object.fromEntries(partialNames.map(id=>[id,fs.readFileSync(safeFile(root,`tools/pages/partials/${id}.html`),'utf8').replaceAll('\r\n','\n').trim()]));}
export const normalized=source=>source.replace(/\s+/g,' ').trim();
export function shell(registry,route,templates){
  const pages=[...registry.existing,...registry.pages.map(p=>({route:`/${p.slug}/`,label:p.navLabel,managed:true,...p.navigation}))];
  const primary=pages.filter(p=>p.header).map(p=>`      <a href="${p.route}"${p.managed?` class="managed-route-link${p.route===route?' active':''}"`:p.route===route?' class="active"':''}>${escape(p.label)}</a>`).join('\n');
  const footer=pages.filter(p=>p.footer).map(p=>`              <a href="${p.route}"${p.managed?' class="managed-route-link"':''}${route==='/privacy/'&&p.route===route?' aria-current="page"':''}>${escape(p.label)}</a>`).join('\n');
  return {header:templates.header.replace('{{primary}}',primary),footer:templates[route==='/privacy/'?'footer-privacy':'footer'].replace('{{footer}}',footer),background:templates[route==='/tournaments/'?'background-tournaments':'background'],managedNavigation:registry.pages.some(p=>p.navigation.header||p.navigation.footer)};
}
export function segments(source){
  const pick=re=>{const matches=[...source.matchAll(re)];must(matches.length===1,'PAGE_SHELL','Missing/duplicate shell region.');return matches[0][0];};
  const header=pick(/<header\b[\s\S]*?<\/header>/g),footer=pick(/<footer\b[\s\S]*?<\/footer>/g),body=pick(/<main\b[\s\S]*?<\/main>/g);
  const start=source.indexOf('>',source.indexOf('<body'))+1,end=source.indexOf('<div class="shell radar">');must(start>0&&end>start,'PAGE_SHELL','Unsupported body shell.');
  return {header,footer,background:source.slice(start,end).trim(),body};
}
export function patchShell(source,expected){const before=segments(source);for(const id of ['header','footer','background'])if(normalized(before[id])!==normalized(expected[id]))source=source.replace(before[id],expected[id].replaceAll('\n',source.includes('\r\n')?'\r\n':'\n'));const style='<link rel="stylesheet" href="/styles/site-pages.generated.css">';if(expected.managedNavigation&&!source.includes(style))source=source.replace('<link rel="stylesheet" href="/styles/command-deck.css">','<link rel="stylesheet" href="/styles/command-deck.css">'+(source.includes('\r\n')?'\r\n':'\n')+style);else if(!expected.managedNavigation)source=source.replace(/\r?\n<link rel="stylesheet" href="\/styles\/site-pages.generated.css">/,'');return source;}
export function pageDocument(page,registry,root,templates){
  const {body}=composition(page,registry,root),parts=shell(registry,`/${page.slug}/`,templates),title=escape(page.title),description=escape(page.description),canonical=origin+`/${page.slug}/`;
  return `<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">\n<meta name="theme-color" content="#06090b">\n<meta name="description" content="${description}">\n<title>${title}</title>\n<link rel="canonical" href="${canonical}">\n<meta property="og:type" content="website">\n<meta property="og:site_name" content="KrispyKP">\n<meta property="og:title" content="${title}">\n<meta property="og:description" content="${description}">\n<meta property="og:url" content="${canonical}">\n<meta property="og:image" content="https://krispykp.com/assets/logo.png">\n<meta name="twitter:card" content="summary">\n<meta name="twitter:title" content="${title}">\n<meta name="twitter:description" content="${description}">\n<meta name="twitter:image" content="https://krispykp.com/assets/logo.png">\n<link rel="stylesheet" href="/styles/site.css">\n<link rel="stylesheet" href="/styles/radar-game.css">\n<link rel="stylesheet" href="/styles/command-deck.css">\n<link rel="stylesheet" href="/styles/site-pages.generated.css">\n<link rel="apple-touch-icon" sizes="180x180" href="/assets/favicon/apple-touch-icon.png">\n<link rel="icon" type="image/png" sizes="32x32" href="/assets/favicon/favicon-32x32.png">\n<link rel="icon" type="image/png" sizes="16x16" href="/assets/favicon/favicon-16x16.png">\n<link rel="manifest" href="/site.webmanifest">\n</head>\n<body class="page-managed">\n${parts.background}\n<div class="shell radar">\n${parts.header}\n${body}\n${parts.footer}\n</div>\n<script src="/data/radar-effects.js"></script>\n<script src="/data/radar-game.js"></script>\n<script src="/data/site-ui.js"></script>\n</body>\n</html>\n`;
}
export function generatedStyle(registry,root){if(!registry.pages.length)return '/* Website-owned managed page projection; no managed pages. */\n';return '/* Website-owned bounded managed page projection. */\n.page-managed { --channel-label:"COMMUNITY CHANNEL"; --page-rgb:84,188,224; }\n.page-managed main { overflow-wrap:anywhere; }\n.managed-route-link { white-space:normal; overflow-wrap:anywhere; min-width:0; max-width:100%; }\n.managed-body { display:grid; gap:20px; min-width:0; }\n.managed-body > *, .managed-grid > * { min-width:0; }\n.managed-grid { display:grid; gap:20px; }\n.managed-image { display:block; max-width:100%; height:auto; }\n'+registry.pages.map(p=>composition(p,registry,root).css).join('');}
export function sitemap(registry){return '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+[...registry.existing.map(p=>p.route),...registry.pages.map(p=>`/${p.slug}/`)].map(route=>`  <url><loc>${origin}${route}</loc></url>`).join('\n')+'\n</urlset>\n';}
export const shellHash=templates=>sha(JSON.stringify(templates));
