import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {chromium} from 'playwright-core';
import {createStaticServer} from '../validate-browser.mjs';
import {findChromiumExecutable} from '../validation-common.mjs';
import {inventory,sha} from '../management/files.mjs';
import {loadPages} from './contract.mjs';
import {previewBridge} from '../layout/bridge.mjs';
import {checkPageFoundation} from './render.mjs';
import {copyInventory} from './fixtures.mjs';
import {build} from './build.mjs';
import {segments} from './shell.mjs';

const root=process.cwd(),candidate=path.resolve(process.argv[2]),out=path.resolve(process.argv[3]),capture=path.resolve(process.argv[4]);const before=inventory(candidate),loaded=loadPages(candidate),mapping=loaded.mappings.find(p=>p.id==='page.community-note');assert.ok(mapping);
const source=await createStaticServer(root),draft=await createStaticServer(candidate),browser=await chromium.launch({executablePath:findChromiumExecutable(),headless:true}),results=[];fs.mkdirSync(capture,{recursive:true});
const pass=(name)=>{results.push({name,status:'PASS'});console.log('PASS '+name);};
try{
  await checkPageFoundation(browser,draft.baseUrl,candidate);pass('two managed templates at eleven threshold widths: source/map/grid/keyboard/skip/menu/image/Radar/overflow');
  const context=await browser.newContext({viewport:{width:1024,height:900},deviceScaleFactor:1.5,reducedMotion:'reduce'});await context.route('**/*',r=>r.request().url().startsWith(source.baseUrl)||r.request().url().startsWith(draft.baseUrl)?r.continue():r.abort());const page=await context.newPage();await page.goto(draft.baseUrl+mapping.route);await page.evaluate(()=>{window.messages=[];window.chrome={webview:{postMessage:m=>window.messages.push(m)}};});
  const settings={origin:draft.baseUrl,sessionId:'E1_test_session_12345',documentId:'E1_test_document_12345',candidateSha256:sha(JSON.stringify(before))},bindings=mapping.components.map(n=>({...n,operations:['setPage']})),bridge=previewBridge(settings,bindings,{attribute:'data-kkp-page-id',routes:[mapping.route,mapping.route+'index.html']});
  await page.evaluate(bridge.script);const command=async value=>page.evaluate(r=>window.__kkpLayoutBridgeV1.command(r),{...settings,...value});assert.equal(await command({kind:'mode',mode:'edit'}),true);await page.locator('[data-kkp-page-id="page.community-note.copy"]').click();const selected=await page.evaluate(()=>window.messages.filter(m=>m.kind==='selectionGeometry').at(-1));assert.equal(selected.id,'page.community-note.copy');assert.equal(selected.units,'css-px');assert.equal(selected.devicePixelRatio,1.5);pass('actual new-page click uses current CSS geometry with bounded identity');
  assert.equal(await command({sessionId:'wrong',kind:'select',id:'page.community-note.cta'}),false);assert.equal(await command({candidateSha256:'A'.repeat(64),kind:'mode',mode:'interact'}),false);assert.equal(await command({kind:'createPage',value:{}}),false);pass('stale session/candidate and operation-shaped bridge commands refused');
  await page.evaluate(()=>scrollTo(0,300));await page.setViewportSize({width:390,height:900});await page.waitForTimeout(100);const geometry=await page.evaluate(()=>window.messages.filter(m=>m.kind==='selectionGeometry').at(-1));assert.equal(geometry.viewport.width,390);assert.ok(geometry.revision>selected.revision);pass('scroll/profile resize refreshes ephemeral selection');
  await page.keyboard.press('ArrowDown');await page.keyboard.press('Escape');assert.ok(await page.evaluate(()=>window.messages.some(m=>m.kind==='selectionCleared')));pass('keyboard component order and Escape clearing');
  await page.evaluate(bridge.script);assert.equal(await page.locator('[data-kkp-private-overlay]').count(),1);await command({kind:'mode',mode:'edit'});await command({kind:'select',id:'page.community-note.copy'});await page.locator('[data-kkp-page-id="page.community-note.copy"]').evaluate(e=>e.setAttribute('data-kkp-page-id','tampered'));await page.waitForTimeout(100);assert.ok(await page.evaluate(()=>window.messages.some(m=>m.kind==='selectionInvalidated')));await page.locator('[data-kkp-page-id="tampered"]').evaluate(e=>e.setAttribute('data-kkp-page-id','page.community-note.copy'));pass('reattach replaces overlay and live map drift invalidates selection');
  await page.locator('[data-kkp-page-id="page.community-note.copy"]').evaluate(e=>e.after(e.cloneNode(true)));await assert.rejects(()=>page.evaluate(bridge.script),/render map disagrees/);await page.locator('[data-kkp-page-id="page.community-note.copy"]').last().evaluate(e=>e.remove());pass('duplicate live identities refuse a prepared bridge');
  await page.evaluate(bridge.script);await command({kind:'mode',mode:'interact'});await page.locator('main .btn').click();assert.ok(page.url().endsWith('/about/'));assert.equal(await page.locator('[data-kkp-private-overlay]').count(),0);await assert.rejects(()=>page.evaluate(bridge.script),/route has no declared/);pass('interaction navigation tears down and wrong route cannot attach');await context.close();
  const visualContext=await browser.newContext({reducedMotion:'reduce'});await visualContext.route('**/*',r=>r.request().url().startsWith(source.baseUrl)||r.request().url().startsWith(draft.baseUrl)?r.continue():r.abort());const visual=await visualContext.newPage();
  for(const [id,route] of Object.entries(loaded.routes)){for(const width of [390,1440]){await visual.setViewportSize({width,height:900});await visual.goto(draft.baseUrl+route);await visual.screenshot({path:path.join(capture,`${id}-${width}.png`),fullPage:true});}}
  await visual.setViewportSize({width:980,height:900});await visual.goto(draft.baseUrl+'/community-note/');await visual.screenshot({path:path.join(capture,'page.community-note-980.png'),fullPage:true});await visualContext.close();pass('all nine candidate routes captured at mobile/desktop plus medium template');
  const globalRoot=path.join(path.dirname(out),path.basename(out,'.json')+'-global-fixture');assert.ok(!fs.existsSync(globalRoot),'Use a fresh private global fixture destination');copyInventory(candidate,globalRoot,before);
  const bodyBefore=Object.values(loaded.routes).map(route=>{const file=route==='/'?'index.html':route.slice(1)+'index.html';return [file,segments(fs.readFileSync(path.join(globalRoot,file),'utf8')).body];});
  for(const file of ['header','footer','footer-privacy','background','background-tournaments']){const target=path.join(globalRoot,'tools/pages/partials/'+file+'.html');let text=fs.readFileSync(target,'utf8');if(file==='header')text=text.replace('brand-mark">KrispyKP','brand-mark">KrispyKP fixture');else if(file.startsWith('footer'))text=text.replace('footer-brand-title">KrispyKP','footer-brand-title">KrispyKP fixture');else text=text.replace('class="radar-grid"','class="radar-grid" data-shell-fixture="v1"');fs.writeFileSync(target,text);}
  const rebuilt=build(globalRoot,{write:true});assert.equal(rebuilt.outputs.filter(f=>f.endsWith('index.html')).length,9);for(const [file,body] of bodyBefore)assert.equal(segments(fs.readFileSync(path.join(globalRoot,file),'utf8')).body,body);
  const globalServer=await createStaticServer(globalRoot),globalContext=await browser.newContext({reducedMotion:'reduce'});try{await globalContext.route('**/*',r=>r.request().url().startsWith(globalServer.baseUrl)?r.continue():r.abort());const globalPage=await globalContext.newPage();for(const [id,route] of Object.entries(loaded.routes)){await globalPage.setViewportSize({width:1440,height:900});await globalPage.goto(globalServer.baseUrl+route);assert.ok((await globalPage.locator('.brand-mark').textContent()).includes('fixture'));assert.ok((await globalPage.locator('.footer-brand-title').textContent()).includes('fixture'));assert.equal(await globalPage.locator('[data-shell-fixture="v1"]').count(),1);assert.equal(await globalPage.locator('.skip-link').count(),1);await globalPage.screenshot({path:path.join(capture,`global-${id}-1440.png`),fullPage:true});}}finally{await globalContext.close();await new Promise(r=>globalServer.server.close(r));}pass('actual global header/footer/background rebuild reaches seven bespoke and two new pages with exact body preservation');
  const longRoot=globalRoot+'-long';copyInventory(globalRoot,longRoot,inventory(globalRoot));const registryFile=path.join(longRoot,'data/site-pages.json'),registry=JSON.parse(fs.readFileSync(registryFile));registry.pages[0].name='X'.repeat(80);registry.pages[0].navLabel='X'.repeat(40);registry.pages[0].hero.title='X'.repeat(80);registry.pages[0].hero.summary='X'.repeat(600);registry.pages[0].components[0].children[1].text='X'.repeat(2400);registry.pages[0].components[0].children[2].text='X'.repeat(120);fs.writeFileSync(registryFile,JSON.stringify(registry,null,2)+'\n');build(longRoot,{write:true});
  const longServer=await createStaticServer(longRoot),longContext=await browser.newContext({reducedMotion:'reduce'});try{await longContext.route('**/*',r=>r.request().url().startsWith(longServer.baseUrl)?r.continue():r.abort());const longPage=await longContext.newPage();for(const route of Object.values(loaded.routes)){for(const width of [320,390,699,700,701,979,980,981,1024,1440]){await longPage.setViewportSize({width,height:900});await longPage.goto(longServer.baseUrl+route);if(width<=700)await longPage.locator('.nav-toggle').click();assert.ok(await longPage.locator('.managed-route-link, .page-managed main h1, .page-managed main p, .page-managed main .btn').evaluateAll(nodes=>nodes.every(n=>n.scrollWidth<=n.clientWidth+1)),'Long content/menu label clips at '+route+' '+width);assert.equal(await longPage.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);}}}finally{await longContext.close();await new Promise(r=>longServer.server.close(r));}pass('maximum continuous text/CTA/nav labels wrap without container clipping at ninety current/new route thresholds with open compact menus');
  assert.deepEqual(inventory(candidate),before);pass('private bridge/browser/export evidence leaves every candidate byte unchanged');fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify({status:'PASS',results,candidateSha256:settings.candidateSha256,manual:['Native WebView2/WPF DPI and physical input/assistive quality remain unverified.']},null,2)+'\n');
}finally{await browser.close();await Promise.all([new Promise(r=>source.server.close(r)),new Promise(r=>draft.server.close(r))]);}
